"""Add tax field to Group

Revision ID: 295510096993
Revises: 60c5d1b20667
Create Date: 2025-07-28 14:58:20.347241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295510096993'
down_revision = '60c5d1b20667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('tax')

    # ### end Alembic commands ###
