"""updated expense split identificatin method

Revision ID: 55bbfa102fc6
Revises: c685b7ac1985
Create Date: 2025-07-31 23:45:34.870677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bbfa102fc6'
down_revision = 'c685b7ac1985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
