"""removed nullable compulsion on fk

Revision ID: 5dcd9d4388cd
Revises: 295510096993
Create Date: 2025-07-29 15:15:28.507439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcd9d4388cd'
down_revision = '295510096993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('fk_membership_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('fk_membership_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
