"""Add invite_code to Group

Revision ID: 62115a19e0e7
Revises: 55bbfa102fc6
Create Date: 2025-08-02 01:46:51.855051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62115a19e0e7'
down_revision = '55bbfa102fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("uq_group_invite_code", ['invite_code']) 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
