"""Make split user nullable

Revision ID: c685b7ac1985
Revises: 5dcd9d4388cd
Create Date: 2025-07-31 20:44:57.258721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c685b7ac1985'
down_revision = '5dcd9d4388cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('fk_expense_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.alter_column('fk_split_main',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fk_split_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.alter_column('fk_split_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fk_split_main',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('fk_expense_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
